# Generated by Django 3.2.9 on 2021-11-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='idade',
            field=models.PositiveIntegerField(default=0, help_text='Digite sua idade'),
        ),
    ]
